Controllers/AboutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using url_shortener.Models;

namespace url_shortener.Controllers
{
    [Route("/about")]
    public class AboutController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AboutController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {

            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Files", "algorithm_description.txt");

            string text = System.IO.File.ReadAllText(filePath);

            if (text == null)
            {
                text = "No description available";
            }

            ViewBag.Text = text;

            return View(new About() { Text = text});
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(string text)
        {
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Files", "algorithm_description.txt");

            await System.IO.File.WriteAllTextAsync(filePath, text);

            return RedirectToAction("Index");
        }
    }
}

Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using url_shortener.Contexts;
using url_shortener.Models;
using url_shortener.Repositories;

namespace url_shortener.Controllers
{
    [AllowAnonymous]
    [Route("/login")]
    public class AuthenticationController : Controller
    {
        private readonly IRepository<User, int> _repository;

        public AuthenticationController(IRepository<User, int> repository)
        {
            _repository = repository;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "ShortUrl");
            } else if (User.IsInRole("User"))
            {
                return RedirectToAction("Index", "ShortUrl");
            }

            return View();

        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Login", "Password")] User user)
        {
            var usersFromDb = await _repository.GetAll();

            var findUser = usersFromDb.FirstOrDefault(u => u.Login == user.Login && u.Password == user.Password);

            if (findUser != null)
            {

                var claims = new List<Claim>
                {
                    new(ClaimTypes.Name, findUser.Login),
                    new(ClaimTypes.Role, findUser.Role),
                    new(ClaimTypes.NameIdentifier, findUser.Id.ToString())
                };

                var identity = new ClaimsIdentity(claims, "ApplicationCookie");
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync("ApplicationCookie", principal);
                return RedirectToAction("Index", "ShortUrl");
            }
            ViewBag.Error = "Invalid login or password";
            return View("Index", user);
        }

        [AllowAnonymous]
        [Route("/login/info")]
        public IActionResult GetRole()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Ok(new { role = "Unauthorized"});
            } else if (User.IsInRole("Admin"))
            {
                return Ok(new { id = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value, role = "Admin" });
            } else if (User.IsInRole("User"))
            {
                return Ok(new { id = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value, role = "User" });
            } else
            {
                return BadRequest();
            }
        }

        [Route("/logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("ApplicationCookie");
            return RedirectToAction("Index");
        }
    }
}

Controllers/ShortUrlController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using url_shortener.Models;
using url_shortener.Repositories;
using url_shortener.Utilities;

namespace url_shortener.Controllers
{
    [Route("")]
    public class ShortUrlController : Controller
    {
        private readonly IRepository<ShortUrl, string> _repository;

        public ShortUrlController(IRepository<ShortUrl, string> repository)
        {
            _repository = repository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [HttpDelete]
        [Route("short-url/{id}")]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _repository.Delete(id);

            if (result == null)
            {
                return NotFound();
            }
            else
            {
                return Ok(new { success = "true", data = result });
            }
        }

        [HttpPost]
        [Route("short-url")]
        [Authorize]
        public async Task<IActionResult> Add([FromBody] ShortUrlBody body)
        {
            if (_repository.GetAll().Result.Any(url => url.OriginalUrl == body.originalUrl))
            {
                return BadRequest(new {success = "false", message = "This URL already exists" });
            }

            string shortedUrl = ShortUrlService.Short(body.originalUrl);

            var shortUrl = new ShortUrl
            {
                OriginalUrl = body.originalUrl,
                ShortenedUrl = shortedUrl,
                CreationDate = DateTime.UtcNow,
                CreatedBy = body.userId
            };

            ShortUrl result = await _repository.Add(shortUrl);

            if (result != null)
            {
                return Ok(new {success = "true", data = result });
            } else
            {
                return BadRequest(new {success = "false" });
            }
        }

        [HttpGet]
        [Route("{shortUrl}")]
        public async Task<IActionResult> Get(string shortUrl)
        {
            var result = await _repository.Get(shortUrl);

            if (result == null)
            {
                return NotFound();
            }
            else
            {
                return Redirect(result.OriginalUrl);
            }
        }

        [HttpGet]
        [Route("short-url/{id}")]
        [Authorize]
        public async Task<IActionResult> Info(int id)
        {
            
            var result = await _repository.GetAll();

            var findUrl = result.FirstOrDefault(url => url.Id == id);

            if (findUrl == null)
            {
                return NotFound();
            }
            else
            {
                findUrl.ShortenedUrl = $"{Request.Scheme}://{Request.Host}/{findUrl.ShortenedUrl}";
                return View("Info", findUrl);
            }
        }

        [HttpGet]
        [Route("short-url")]
        public async Task<IActionResult> GetAll()
        {
            var result = await _repository.GetAll();

            if (result.ToList().Count() == 0)
            {
                return NotFound();
            }
            else
            {
                return Ok(result.Select(url =>
                {
                    string shortUrl = url.ShortenedUrl;
                    url.ShortenedUrl = $"{Request.Scheme}://{Request.Host}/{shortUrl}";
                    return url;
                }));
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UrlShortener</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body class="h-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                <div class="row w-100">
                    <div class="col-4 d-flex align-items-start ">
                        <a class="text-decoration-none" style="color: black; font-size: 20px; padding-left: 1rem; padding-top: .2rem;" asp-controller="ShortUrl" asp-action="Index">
                            UrlShortener
                        </a>
                    </div>
                    <div class="col-4 d-flex justify-content-center">
                        <div class="justify-content-between">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ShortUrl" asp-action="Index">Urls</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-4 d-flex justify-content-end">
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <span class="pe-2">Username: @User.Identity.Name</span>
                                <span>Id: @User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value</span>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Index">Login</a>
                            }
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" @* class="d-flex justify-content-center align-items-center" *@ style="height: calc(100% - 73px);">
        @RenderBody()
    </main>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>